blank_issues_enabled: false
contact_links:
  - name: Todo
    about: Create new todo for atomiklabs.io project
    url: https://github.com/atomiklabs/atomiklabs.io/issues/new?template=todo&projects=atomiklabs/1&labels=atomiclabs.io
